
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
export const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

console.log('[Supabase Client] 🔍 ENV VARS CHECK:');
console.log('[Supabase Client] - VITE_SUPABASE_URL:', supabaseUrl ? 'DEFINED' : 'UNDEFINED');
console.log('[Supabase Client] - VITE_SUPABASE_ANON_KEY:', supabaseAnonKey ? `DEFINED (${supabaseAnonKey.substring(0, 20)}...)` : 'UNDEFINED');

// Use ANON key in the client (browser). For non-browser environments (e.g. SSR),
// it's expected that separate server-side clients are created with the appropriate keys.
const supabaseKey = supabaseAnonKey;

console.log('[Supabase Client] Initializing with:');
console.log('[Supabase Client] URL:', supabaseUrl);
console.log('[Supabase Client] Using KEY: ANON (Normal)');
console.log('[Supabase Client] Key (first 20 chars):', supabaseKey?.substring(0, 20) + '...');

// Validate environment variables
if (!supabaseUrl || !supabaseKey) {
  const missingVars = [];
  if (!supabaseUrl) missingVars.push('VITE_SUPABASE_URL');
  if (!supabaseKey) missingVars.push('VITE_SUPABASE_ANON_KEY');
  
  const errorMsg = `Missing required environment variables: ${missingVars.join(', ')}. ` +
    'Please check your .env file or server environment variables configuration.';
  console.error('[Supabase Client] ERROR:', errorMsg);
  throw new Error(errorMsg);
}

// Validate URL format
try {
  new URL(supabaseUrl);
} catch (error) {
  throw new Error(`Invalid Supabase URL format: ${supabaseUrl}`);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Defensive runtime check: ensure we are NOT running with the SERVICE_ROLE key
function looksLikeJwt(token?: string) {
  return typeof token === 'string' && token.split('.').length === 3;
}

function parseJwtPayload(token: string) {
  try {
    const parts = token.split('.');
    const payload = parts[1];
    const json = atob(payload.replace(/-/g, '+').replace(/_/g, '/'));
    return JSON.parse(json);
  } catch (e) {
    return null;
  }
}

if (looksLikeJwt(supabaseKey)) {
  const payload = parseJwtPayload(supabaseKey as string);
  if (payload && (payload.role === 'service_role' || (payload['https://hasura.io/jwt/claims'] && payload['https://hasura.io/jwt/claims'].role === 'service_role'))) {
    console.error('[Supabase Client] FATAL: Detected a SERVICE_ROLE key running in the browser.');
    console.error('[Supabase Client] This is a critical security issue — remove any SERVICE_ROLE key from your frontend build environment.');
    console.error('[Supabase Client] Aborting client initialization to avoid leaking privileged credentials.');
    throw new Error('Supabase service_role key detected in frontend environment. Remove it from build env.');
  }
}

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'leadflow2-frontend',
    },
  },
});

console.log('[Supabase Client] ✅ Client created successfully');
